# Generated by Django 4.1.6 on 2023-05-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='my_bid',
            new_name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
